### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [mt1006/mc-mocap-mod#18]
1.Can we add CMDCam as a soft dependency, triggering Mocap when CMDCam is playing?
2.Add shortcut keys for quick control, such as play, pause, replay, and cancel.

**Comment by mt1006** [comment]
1. It should be possible, but I think the best way to do that would be by adding possibility to add command execution to the scene. I don't have plans on expanding scene capabilities well beyond what they're now, so I thought about creating a new mod which would be using Mocap's API and allow to create much more complex scenes and even things like interactive dialogs, logic, etc. The problem is that there isn't even API yet, which I plan to add in the 1.4 version. As for now, if you want to synchronize start of Mocap and CMDCam scene, try using command blocks with ```/cam-server``` command.

3. Maybe I'll add this in the next version.

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱

**Comment by Thexiaoyuqaq** [comment]
Okay, thank you!
