### ISSUE TITLE
how do I turn the player into slim mode?

### ISSUE THREAD

**Issue by m3raak1** [mt1006/mc-mocap-mod#24]
I'm adding a recording to a scene, then I put it in from file and add the skin, it's in the slim folder but the body of the default player remains, I don't know how I can fix this

here is the command I am using:
/mocap scenes addTo .ilb ilb 0 0 0 0 Bea from_file slim/beatrice

**Comment by mt1006** [comment]
From what I've checked it should work fine, at least on Fabric 1.20.4. First, is it the problem that player body is normal instead of slim or that skin isn't applied at all? Also, what Minecraft version and mod loader are you using and are you playing on singleplayer or multiplayer?

**Comment by m3raak1** [comment]
the problem is that player body is normal instead of slim, I'm using the mod in singleplayer in version 1.16.5 in this specific version Mocap-FORGE-1.16.5-1.3.4

**Comment by mt1006** [comment]
I've tried this exact version and it works fine. I don't really have an idea what may be the cause, but these are my suggestions what you can do:
1. Double check if the recording in the scene has a skin with `slim/`. Then maybe try to recreate this issue on another world or version. Also compare how player arms with slim skin compare to these with normal skin, as you may mistakenly think that slim arms are normal.
2. If you're using any other mods try without them. If it will fix the issue, try to find which mod it was caused by and write back.
3. If two first steps won't help, write down exact steps to recreate this issue, or better, create world on which you've already created scene and send it with command to execute.

**Comment by m3raak1** [comment]
I got it thank you very much. I tested the steps and the second one solved it.

The problem is the tl_skin_cape mod from tlauncher, I removed it and it solved the problem.

**Comment by mt1006** [comment]
Good to know. I will probably add some warning in the next version regarding this mod. Also from what I've heard, tlauncher is spooky at best and spyware at worst, so I would consider changing it to another "cracked" launcher like UltimMC (https://github.com/UltimMC/Launcher).
