### ISSUE TITLE
The game sees the commands as cheats

### ISSUE THREAD

**Issue by NachoWarlock** [mt1006/mc-mocap-mod#29]
I am running a hardcore and normal world in 1.20.1 and want to capture mocap video but the hardcore world does not allow cheats so I can not use mocap as Minecraft sees the mocap commands as cheats.

**Comment by mt1006** [comment]
The `/mocap` command requires "enabling cheats" (operator permissions) because it's a server-side mod and playback have actual impact on the world and can actually be used for "cheating" (e.g. it can be used to duplicate blocks). In general, mocap is not suited for recording survival/hardcore gameplay, but for creating complex scenes with multiple players or entities. If you want to record your hardcore gameplay you should rather use client-side mods like replay mod. If you really want to use mocap try enabling cheats using "open to LAN" button.
