### ISSUE TITLE
Random arm model

### ISSUE THREAD

**Issue by Babagi75** [mt1006/mc-mocap-mod#36]
Hi, so i found the bug where i set the skin non slim model from my file on every actors. When replaying scene, it sometimes become slim on random actors. To make it to non slim model, i have to keep replaying. Maybe you can add option for non slim model to prevent this issue.

Appreciate, mate. It's very cool mod anyway.

**Comment by mt1006** [comment]
Thanks, but unfortunately I wasn't able to reproduce this issue. First, tell me what Minecraft version, mod version and mod loader are you using?. Second, details how to reproduce this issue. I think the best way would be to create a new world, make a scene that reproduces this issue and sending the save here.

**Comment by Babagi75** [comment]
I am using Minecraft 1.20.1 Iris+fabric.
Current filming in here : https://www.mediafire.com/file/f4bx1olpgdlib22/Nusakarta_v0.2.rar/file
There are 3 example of my custom skin, every actors supposed to be non slim arms.

**Comment by mt1006** [comment]
I tested it and it still works fine for me. I would suggest you renaming skin files to use lowercase letters only. I had to do it on Linux because it's case-sensitive and skins weren't even loading, and iirc there were some issues with uppercase letters with Mocap on Windows as well. If it still won't work, try to disable every mod other than Fabric API and Mocap.

**Comment by Babagi75** [comment]
Nothing change after i rename it all. And yeah, probably mocap is conflicted with some of my other mods, but these mods is suits me for filmmaking, i can't remove any of my current mods i have.

Just uploaded today : https://www.youtube.com/watch?v=SQktp95toEY
In 0:12 you notice their arms is changed.

**Comment by mt1006** [comment]
You mean that removing all other mods fixes the issue? If so, send list of mods or modpack.

**Comment by Babagi75** [comment]
Idk yet, but maybe.
Here my mods i'm using : https://www.mediafire.com/file/79zt4falj4afzrf/mods.rar/file

**Comment by mt1006** [comment]
I'll take a look at them tomorrow

**Comment by mt1006** [comment]
It's some compatibility issue with HD Skins. I'll try to fix it soon.

**Comment by Babagi75** [comment]
Thank you so much. Also add compatibility with emotecraft if you don't mind.

**Comment by mt1006** [comment]
First of all, as for emotecraft compatibility, I'll try to add it in the future.

As for your issue. I have patch ready, but I won't be releasing it as the next version. It's more of the issue on the side of HD Skins than Mocap, and fixing it on my side requires to call check each frame for every rendered player. Although it sounds bad, performance impact is minimal and not noticeable, yet I would still feel bad releasing it. Because of that I will only release patched binary for 1.20.1 on github along with source code, if you or anyone else would like to use it.

https://github.com/mt1006/mc-mocap-mod/releases/tag/Mocap-1.3.8-hd_skins_fix

Let me know if you have any issues with this binary. Also, from what I've tested 1.21.1 version isn't affected by this issue.
Anyway, thanks for reporting this issue.
